name: CIJavaBuild

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '[ci skip]') }}
    strategy:
      matrix:
        java: [ '8' ]
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn -B package --file java/pom.xml
      - name: Test with Maven
        run: mvn test --file java/pom.xml
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ServerWebGamePost Java Edition
          path: java/target/ServerWebGamePost-1.0.0.jar
