# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: "20.x"
    - run: npm install --prefix nodejs
    - run: npm ci --prefix nodejs
    - run: npm run build --if-present --prefix nodejs
    - run: npm test --prefix nodejs
    - run: npm pack --prefix nodejs
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ServerWebGamePost NodeJS Edition
        path: nodejs/ServerWebGamePost-1.0.0.tgz
