# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install --prefix nodejs
      - run: npm run build --if-present --prefix nodejs
      - run: npm ci --prefix nodejs
      - run: npm test --prefix nodejs

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com/
          scope: @Creadores-Program
      - run: npm install --prefix nodejs
      - run: npm run build --if-present --prefix nodejs
      - run: npm ci --prefix nodejs
      - run: npm publish 
        working-directory: ./nodejs
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
